### ISSUE TITLE
Broken URL parameter decoding in 0.4.0

### ISSUE THREAD

**Issue by jdknezek** [quirkey/sammy#10]
After upgrading to 0.4.0, the route "#/:message" causes "#/hello%20there" to be interpreted as "hello%2520there"

**Comment by quirkey** [comment]
Dang - I'll have a look at this today, sorry about that.

**Comment by quirkey** [comment]
Hey @jdznezek - Could you give me a little more info about this so I can track it down. Ideally, what browser/platform you're seeing this on and maybe some steps to reproduce. I just wrote a test that I feel should cover this and I'm not seeing any issue.
Thanks for your help!

**Comment by jdknezek** [comment]
Sorry for the delay - couldn't reproduce this at home. O.o  I'm running Google Chrome 4.0.266.0, jQuery 1.3.2 min, CouchDB 0.10.0, jQuery.Couch 0.9.0 and Sammy 0.4.0 min.

I have a route: 

```
app.get('#/recipes/by-ingredient/:ingredient', function(context) {
  db.view('recipes/recipes-by-ingredient', {
    'reduce': false,
    'startkey': [context.params.ingredient],
    'endkey': [context.params.ingredient, {}],
    'success': function(data) {
      context.data = data;

      context.partial('js/views/recipes/by-something.ejs');
    }
  });
});
```

and I have a link:

```
<a href="#/recipes/by-ingredient/ground meat">ground meat</a>
```

Whenever the route is run, this is the request that Chrome executes:

```
.../_view/recipes-by-ingredient?reduce=false&startkey=%5B%22ground%2520meat%22%5D&endkey=%5B%22ground%2520meat%22%2C%7B%7D%5D
```

However, I can't reproduce it at home, so I doubt now that Sammy is the culprit.  Sorry for the trouble. =/

**Comment by quirkey** [comment]
Well, your app looks really cool ;) Maybe try pre-escaping the spaces in the links? Let me know if you find anything else.

**Comment by quirkey** [comment]
Pulled in a patch from @jdknezek that does decoding. Closing.
