### ISSUE TITLE
Mustache/Handlebars partials not working

### ISSUE THREAD

**Issue by ghost** [quirkey/sammy#100]
I've done exactly what the documentation says to do, and regardless of which plugin I use (Mustache or Handlebars), Sammy dies and never renders anything with an:

uncaught exception: [object Object]

Example app here:

https://github.com/nsdpt/SammyTest

**Comment by ghost** [comment]
The documentation is just flat out wrong. The line that reads

`context.partials = response;`

Should probably be something like

`context.partials = { hello_friend: response };`

and 

`context.hello_friend = {name: this.params.friend};`

should read

`context.hello_friend = { friend: context.params.friend };`

**Comment by ghost** [comment]
Having rectified that issue in my own code, the Mustache plugin now works correctly, but Handlebars does not interpolate the appropriate value into the nested partial's output, so what I end up with when visiting:

`http://sammytest/#/hello/bob/to/carol`

is:

`Hey, bob! Say hello to your friend !`

So for Handlebars, we seem to need something like

```
$.get('mypartial.hb', function(response)
{
    context.partials        = { hello_friend: response };
    context.name            = context.params.name;
    context.friend          = context.params.friend;

    context.partial('mytemplate.hb');
}); 

```

**Comment by endor** [comment]
thanks nsdpt for noticing those bugs!
