### ISSUE TITLE
window.console in IE8

### ISSUE THREAD

**Issue by yeungda** [quirkey/sammy#11]
When using IE8 with developer tools to open a Sammy application, the application does not work.  This is because Sammy is calling the function window.console.log.apply, which causes IE8 to fail with the error "object does not support this property or method".

Sammy has a guard to prevent this sort of thing from happening - which is to check whether window.console exists before calling the function.  Unfortunately, IE8 with developer tools has a window.console, but does not have the log.apply method Sammy was expecting to be present.

Confirmation of this strange behaviour here: 

http://stackoverflow.com/questions/690251/what-happened-to-console-log-in-ie8/1262103#1262103

"It's worth noting that console.log in IE8 isn't a true Javascript function. It doesn't support the apply or call methods." - James Wheare

Here's how we got the application back to a working state, courtesy of my collegue, pat.  In this case, the logging will not work for IE:

var isMSIE = /_@cc_on!@_/false;

if (!isMSIE && typeof window.console !== 'undefined') {
    Sammy.addLogger(function() {
        window.console.log.apply(window.console, arguments);
    });
} else if (!isMSIE && typeof console !== 'undefined') {
    Sammy.addLogger.push(function() {
        console.log.apply(console, arguments);
    });
}

**Comment by quirkey** [comment]
Hey yeungda

I took a slightly different approach to getting around this by testing to make sure that console.log has the apply method. I just pushed this to master after testing it in IE8/parallels on my mac. Please test it out and let me know if it fixes for you.
--AQ

**Comment by quirkey** [comment]
Tested and fixed in master. Closing
