### ISSUE TITLE
JSON-Plugin not working in IE6

### ISSUE THREAD

**Issue by cjk** [quirkey/sammy#12]
Sammy is a great framework, thanks for sharing it!

Too bad I (and probably many others) still need to support IE6.

Adding...

...
this.use(Sammy.JSON);
...

in IE6 causes an exception to be raised in IE6. Works fine in FF 3.x.

When I add the json2.js library to the HTML-header, the error disappears, but that is not how it's supposed to be, right?

**Comment by quirkey** [comment]
Hey CJK

I just pushed a commit to master that should fix this issue. I tested in parallels/IE6 on my mac, but please test and let me know if it works for you as well.
Thanks!

**Comment by quirkey** [comment]
Just pushed Sammy 0.4.1 which should fix this issue.

**Comment by cjk** [comment]
Confirmed: the javascript-errors in IE6 are indeed gone with the 0.4.1 release. Great, thanks for fixing this so quickly!
