### ISSUE TITLE
this.around(), when redirecting, calls the app but will not render the content

### ISSUE THREAD

**Issue by kirkbushell** [quirkey/sammy#120]
As based on the example in the sammy js site, I am doing an authorization check for a user, and if they are not logged in, redirecting them to the #/users/login/ screen. What's interesting, is that if I go directly to that URL, it works - but when redirecting, the action is called (route is found), however none of the code actually seems to be executed (partial doesn't get placed in main.etc.). Any ideas?

**Comment by quirkey** [comment]
Are you calling `callback()` in a succesful scenario?

**Comment by kirkbushell** [comment]
We found out what the problem was - it was actually something entirely different. Sorry for wasting your time.
