### ISSUE TITLE
How to create a "modal" window?

### ISSUE THREAD

**Issue by drozzy** [quirkey/sammy#123]
Since Sammy.js is reliant on one page model, how can one create a "modal" window (with multiple views).
For example, something like Amazon's preview panel.

I've asked this question on SO, but it seems Sammy.js developers are not there often:
http://stackoverflow.com/questions/8827136/modal-dialog-in-sammy-js

**Comment by quirkey** [comment]
There are a bunch of discussions related to this on the mailing list:
https://groups.google.com/group/sammyjs/search?group=sammyjs&q=modal&qt_g=Search+this+group

**Comment by drozzy** [comment]
Yeah, but none of them really show "amazon" style modal window - where you can actually click around, like next/previous page etc. The examples simply popup a div with static html.
