### ISSUE TITLE
When Sammyjs meets FusionCharts and IE

### ISSUE THREAD

**Issue by shinyzhu** [quirkey/sammy#126]
The charts can not show themselves sometimes when navigating from one route to another in IE but Firefox or Chrome is ok.

Well, I know this problem is totally complicated.

I'm building a web application with sammyjs and the application show some charts on some views with FusionCharts, I create those charts with FusionCharts.js. The code:

app js:

```
var app = Sammy('#content', function () {
    this.use('Template', 'htm');
    this.get('#/', function (context) {
        this.partial('views/home.htm').then(function () {
            //FusionCharts.js required
        var chart = new FusionCharts({
            swfUrl: 'charts/MSCombi2D.swf',
        id: 'chart_sales',
        width: 400,
        height: 300,
        debugMode: false,
        registerWithJS: true
        });

        chart.setXMLUrl('chartsources/valid_sales.xml');
        chart.render('chart_div');
        });
    });
});
```

**Comment by jeremyckahn** [comment]
Can you provide a link to a live example of the bug?
