### ISSUE TITLE
routes don't appear to work as expected in IE8 since 0.4

### ISSUE THREAD

**Issue by nuex** [quirkey/sammy#13]
Just tested a 0.4 sammy app in IE8 and it appears that only the first route (i.e. app.run('#/') ) works. If I click a link that goes to a different route, nothing happens.

After reverting to 0.3.1 everything seems to work fine.

**Comment by quirkey** [comment]
Hey nuex

Can you try using the _latest_ master and see what that does for you? I just fixed an issue with IE8 and console.log that was causing problems for others. 
Thanks,
--AQ

**Comment by yeungda** [comment]
Hi quirkey,

thanks again for your work on sammy.

I have encountered this problem too.  IE8's window object has the onhaschange property, so sammy is using the event based handling of hash changes in HashLocationProxy.  Unfortunately, IE8 only fires the event in "IE8 mode".  This means when IE8 is in Quirks mode, or IE7 mode, sammy does not receive hash change events and sammy apps don't work very well.

one way to make sammy these other modes could be to use polling for IE8 when it is not in IE8 mode.  Here's an example of how the current test could be changed to do this:

if ('onhashchange' in window && (window.navigator.appName == "Microsoft Internet Explorer" ? document.documentMode > 7 : true)) {
  // use hash change event
else {
  // use polling
}

i found this article useful in explaining the various modes: http://msdn.microsoft.com/en-us/library/cc288325(VS.85).aspx

i also found the diagram in this article useful in understanding how IE8 chooses it's mode: http://blogs.msdn.com/ie/archive/2010/03/02/how-ie8-determines-document-mode.aspx

**Comment by quirkey** [comment]
Hey yeungda

I would _really_ _really_ like to keep browser specific checks out of Sammy if possible. I need to do some tests to see if theres any other way to check for the hashchange event without version/browser specific code.
Would love to hear other ideas, too.
--AQ

**Comment by quirkey** [comment]
Fix hashchange events in IE8 when compatibility mode is turned on. Closed by 83c731e77de54602d4727ab782ea14c6adfc63e9

Thanks to a very smart idea from Brian Mitchell (binary42) I was able to avoid using specific browser checks. Instead, the proxy assumes that the hashchange
needs to be faked with polling, and then once (if) a native hash change event occurs, it stops polling.

**Comment by stromnet** [comment]
Hi,

it seems Sammy polls the hash every 50ms by default, and the reason seems to originate from this ticket. Is this still relevant, or can it be avoided in any way?
I've got an app which I usually open and keep open without navigating anywhere, it seems wasteful to poll for state-changes this often when there really is no need to, especially on battery powered devices.
A flag to override this perhaps (i.e. for apps which explicitly does not support such old browsers as IE8)?

Johan
