### ISSUE TITLE
make use of Mustache's partials

### ISSUE THREAD

**Issue by bsingr** [quirkey/sammy#14]
currently we can use only template and data:

var mustache = function(template, data) {
  return Mustache.to_html(template, $.extend({}, this, data));
};

wouldn't it be useful to have something like:

var mustache = function(template, data, partials) {
  return Mustache.to_html(template, $.extend({}, this, data), ....use-partials-here...);
};

cheers,
-dpree

http://github.com/dpree/sammy/commit/ce0ab95488772a3b86da2655bb935e0547dc49d5

**Comment by quirkey** [comment]
This was pulled into master a while ago.
