### ISSUE TITLE
load caching .json URLs

### ISSUE THREAD

**Issue by cyx** [quirkey/sammy#142]
Hi

I've investigated the code for load and if I understand correctly, if the location ends in .json,
it shouldn't be cached.

This isnt' the case (at least in 0.7.1). I've corrected it in our project's copy of sammy.js, but would like
to know if this is indeed the desired behavior.

Here's a gist of the diff:

https://gist.github.com/c4e07ffdd27186e29566

Thanks,
cyx

**Comment by cyx** [comment]
Oops, I made a mistake in the previous diff. This one is better:

https://gist.github.com/d5d89054d525107d9f36

**Comment by endor** [comment]
Thanks cyx for finding this bug. The attached commit should fix it. I also added some tests to make sure it's understandable what's supposed to happen in the code.

**Comment by cyx** [comment]
Excellent @endor. Looking forward to the next release then :-)
