### ISSUE TITLE
Sammy is eating cmd-click on the Mac

### ISSUE THREAD

**Issue by pbiggar** [quirkey/sammy#144]
On OSX, Cmd-click is supposed to be the same as middle-click. However, Sammy is not propagating events for cmd-clicks, though it does it correctly for middle-clicks. I asked about this on StackOverflow and the discussion is useful: http://stackoverflow.com/questions/10660360/command-click-doesnt-open-a-new-tab-but-middle-click-does/

**Comment by endor** [comment]
Thanks pbiggar and o.v..
