### ISSUE TITLE
Calling refresh() changes the path

### ISSUE THREAD

**Issue by pseudoname** [quirkey/sammy#146]
The path before refresh() is called is http://www.mydomain.com/App/#/Collection/123 after refresh is called it changes to http://www.mydomain.com/App/#

I need to understand why this is happening and how to prevent it or if this is a bug. I need the URL to remain the same after I call the refresh() method.

Thanks

**Comment by endor** [comment]
Can you make a small sample app or a gist of your code to reproduce? That would be very helpful in debugging.

**Comment by pseudoname** [comment]
I have a base URL : http://www.mydomain.com when user logs in I redirect them to http://www.mydomain.com/App/#/
At the page for http://www.mydomain.com/App/#/ I have set up Sammy with the following routes

self.sammyRouteApp = Sammy(function () {

```
    this.get('#/Collection/:collectionID', function (context) {
    });
    this.get('#/Collection/Public/:collectionID', function (context) {
    });
    this.get('#/', function (context) {
        if (self.member.SessionToken == '') {
            self.checkLoginStatus(function (result) {
                if (result.IsSuccess) {
                    if (result.Data.toString() != "") {
                        $("#fblogin").text("Logout");
                        context.app.runRoute("get", "#/Collection/" + self.member.RootCollectionID);

                    }
                }

            });
        }
        else {
            context.app.runRoute("get", "#/Collection/" + self.member.RootCollectionID);
        }
    });
```

});
self.sammyRouteApp.run();

On a click of a button I set the location.hash="/Collection/" + collectionID. This runs the #/Collection/:collectionID route and the address bar shows http://www.mydomain.com/App/#/Collection/123 Now when user clicks another button I call self.sammyRouteApp.refresh(); This runs the route again (essentially refreshing the data) but the address bar now shows http://www.mydomain.com/App/# instead of http://www.mydomain.com/App/#/Collection/123 

I need the URL in the address bar to stay the same when I call the refresh method. I hope that explains my situation a little better. Let me know if you have any further questions. 

Thanks for the help.

**Comment by endor** [comment]
I tried to recreate this, but without success. For me it is still the same URL after the refresh. Here's the code I used:

```
var app = $.sammy(function() {
  this.get('#/', function() {});

  this.get('#/a/:id', function() {
    alert(this.params.id);
  });
});

$(function() {
  app.run('#/');

  $('#button1').click(function() {
    location.hash = '/a/2';
  });

  $('#button2').click(function() {
    app.refresh();
  });
});
```

**Comment by endor** [comment]
Still a valid issue?

**Comment by pseudoname** [comment]
Turns out the button was implemented as an anchor tag and the href on that was set to # hence the URL change. Not a problem with the library.

Thanks
