### ISSUE TITLE
form action='.' and history trouble

### ISSUE THREAD

**Issue by nskeip** [quirkey/sammy#149]
Hi!

I got a form with action='.' (form action="" gives the same result)

Before I used Sammy, it worked fine.

For example: if I was at **/my/nested/page/** it the data to the same addres.

BUT:

When I included sammy 0.7.1 script, I jump from **/my/nested/page/** to the site root:

**/?some_key=some_value&** instead of **/my/nested/page/?some_key=some_value&**.

Checked on Google Chrome 20.0.11.1132.57 and Mozilla Firefox 13.0.1.

_update:_
maybe it's my fault, because I starded the app like this:
app.run(); // without parameters

Using `app.run('#/');` seems to work fine

**Comment by endor** [comment]
Is this still an issue for you? If so, would it be possible to try this somewhere or to have a minimalist example of the problem in a gist?

**Comment by nskeip** [comment]
okay, I'll do it and post a link here

**Comment by nskeip** [comment]
Sorry to make you waiting - I will send the example during this week.
