### ISSUE TITLE
Use of $.isPlainObject in contextMatchesOptions means that objects rules cannot be used to match routes

### ISSUE THREAD

**Issue by andimclean** [quirkey/sammy#156]
The fix for Issue  #112 was to introduce a call to $.isPlainObject. But this does not check if an object is empty, it merely checks if an object is a plain old javascript object, rather than a function or a string.

$.isPlainObject({path: '#home'}) === true

This means that the examples given in the documentation for contextMatchesOptions that use object syntax no longer work.

the line could be amended to:

if (typeof options === 'undefined' || ($.isPlainObject(options) && $.isEmptyObject(options)) {

**Comment by endor** [comment]
hey andi,

I am not sure what you are referring to. Looking at https://github.com/quirkey/sammy/blob/master/lib/sammy.js#L1122 shows me that there's no isPlainObject, but already a isEmptyObject. Is that not correct?

**Comment by Rcomian** [comment]
Yes, I'm confused as well. I was with Andi as we tracked this problem down. I'm looking in to how we managed to get such out of date code.

This is clearly not a bug anymore - it was fixed 4 months ago. It can be closed, cheers.
