### ISSUE TITLE
loadPartials only in render context?

### ISSUE THREAD

**Issue by magicwrites** [quirkey/sammy#161]
Hey,

When I want to load partials using the loadPartials() at the start of the route execution, I am left with "Sammy.Object: {} has no method 'loadPartials'" error. Shouldn't this method work similary to the load() and automatically work on render context?

Otherwise I am left with weird dummy loads like this:

``` Javascript
var app = Sammy('body', function(){

    app.get('#/website/home', function(context){

        this.load('someDummyFileJustToRunRenderContext.ms')
            .loadPartials({
                'heading': 'heading.ms',
                'footer': 'footer.ms'
            })
            .render('realTemplate.ms')
            .swap();

    });

});
```

When I believe that appropriate would be:

``` Javascript
var app = Sammy('body', function(){

    app.get('#/website/home', function(context){

        this.loadPartials({
                'heading': 'heading.ms',
                'footer': 'footer.ms'
            })
            .render('realTemplate.ms')
            .swap();

    });

});
```

this seems weird enough for me to call it an issue, but please correct me if I am doing something wrong.

**Comment by endor** [comment]
Thanks :)
