### ISSUE TITLE
Conversion of string path to regex in 0.7.1

### ISSUE THREAD

**Issue by ghost** [quirkey/sammy#166]
Why did line 575 in version 0.7.1 change to:

path = new RegExp(path.replace(PATH_NAME_MATCHER, PATH_REPLACER) + "$");

I don't find any route this way. I changed back to:

path = new RegExp("^" + path.replace(PATH_NAME_MATCHER, PATH_REPLACER) + "$");

This way all works fine.

**Comment by endor** [comment]
I am not exactly sure what the reason for the change was, but if you show me a mini example of an app that's not working, maybe I can help you solve the issue.

**Comment by endor** [comment]
Is this still an issue?
