### ISSUE TITLE
Sammy.js with Zepto

### ISSUE THREAD

**Issue by Darcbar** [quirkey/sammy#167]
Is there a version of Sammy that works with Zepto.js?

**Comment by PaulGuo** [comment]
The same question.

**Comment by Darcbar** [comment]
I've decided to use Path.js, a lightweight alternative without dependencies.

https://github.com/mtrpcic/pathjs

**Comment by endor** [comment]
I don't think there is such a port yet. You are welcome to add it though.

**Comment by Darcbar** [comment]
Thanks for the response, I wouldn't know where to start :(

**Comment by PaulGuo** [comment]
@darcbar jHash also a good choice. http://jhash.codeplex.com
