### ISSUE TITLE
chain via next() like expressjs?

### ISSUE THREAD

**Issue by deitch** [quirkey/sammy#168]
I was wondering if there is interest/intention to make Sammy routes chainable like expressjs http://expressjs.com:

``` JavaScript
this.get('/foo',loadFoo,renderFoo,markDone);
```

Each callback would then have a signature as follows:

``` JavaScript
function(context,next) {
}
```

This greatly simplifies app development, as well as having a catch-all at the end. For example, if you want all routes to, when done, send some end-of-processing event, you don't need to put it in each route, you can do:

``` JavaScript
this.get('/foo',a,b,sendEvent);
this.get('/bar',c,d,sendEvent);
```

Or even better

``` JavaScript
this.get('/foo',a,b);
this.get('/bar',c,d);
this.final(sendEvent);
```

The best part is it is completely backwards-compatible. If you run

``` JavaScript
this.get('/foo',function(context){
});
```

it works!

I am actually wrapping my Sammy right now to do that, but would be happy to put in a pull request if you'll take it.

**Comment by endor** [comment]
I am definitely interested. I am just wondering.. what's the advantage over using before/after?

**Comment by deitch** [comment]
Async. Look at the following:

``` JavaScript
this.after(function(){console.log("after");});
this.get('/foo',function(ctx){
   console.log("start of fn");
   $.ajax(opts,function(){
      // do some screen rendering and JS calculation
      console.log("screen ready");
   });
});
```

Then results will be:

```
start of fn
after
screen ready
```

when I really want

```
start of fn
screen ready
after
```

I want my callbacks - and my chaining - to happen async and in the appropriate order.

I just got it working, is very cool, and solves a huge problem for me. 

Also allows lots of chaining in an async fashion:

``` JavaScript
this.get('/foo',loadFoo,mungeFoo,renderFoo);
this.get('/bar',loadBar,mungeBar,renderFoo);
```

**Comment by deitch** [comment]
Tell me if you will take it in, and I will create a pull request.

**Comment by endor** [comment]
Can I please see the code?

**Comment by deitch** [comment]
You'd have to, for the pull request to come through anyways, right? :-)

I need to genericize it from my app out to Sammy, take me until tomorrow probably. I just want to know that you want the interface and style and then I'll send you the pull request. You can always modify/reject it, right?

**Comment by endor** [comment]
Sure :)

**Comment by deitch** [comment]
K, on its way. Look for the pull request by tomorrow.

**Comment by deitch** [comment]
I just updated to the latest master branch from quirkey/sammy. Before starting, I ran the test suite - should make sure it works first - and I am getting a decent number of failures (~9). Is this expected?

**Comment by endor** [comment]
No it's not. I just pulled and I don't see any failures in the tests. You run ruby test/test_server, right?

**Comment by deitch** [comment]
Ha! I just looked and saw the file, and said, "hmm, maybe it doesn't work off of file: URLs?" :-)

Trying now...

**Comment by deitch** [comment]
Oh, much better. 100% of the tests run, 370 passes, 0 failures, in 19.11 seconds. 

_Now_ I can start to work in the code.

**Comment by deitch** [comment]
Do I need to do some sort of "rebuild" before I can run the tests, or do the tests run against the code in ./lib/sammy.js ?

**Comment by deitch** [comment]
Ouch, is all I have to say!

In theory it works. Tests are failing, in #run(), beforeEach hook keeps giving:

```
undefined
[object Object]
```

and then every test in #run() runs out of the 2000ms timeout.

I am sure I broke something, not sure what. It almost looks like apps are running when they are supposed to, and not when they are. When window.location.hash = '' in the beforeEach of run() (around line 270), I check that app.isRunning() the first time, it gives false, and I check each Sammy.apps, but I still get

```
404 Not Found get /
```

**Comment by deitch** [comment]
Yeah. It looks like I am getting a build-up of handlers on #main in beforeEach.

I did the following. I put the following:

``` JavaScript
console.log("before hash "+app.isRunning());
window.location.hash = '';
console.log("after hash");
```

for the window.location.hash = '' around line 270 in application_spec.js

The first test, it goes 

```
before hash false
after hash
```

The second test, it does

```
before hash false
#main Sammy.Application:#main location-changed
#main runRoute get /
#main Sammy.Application:#main run-route
#main Sammy.Application:#main error
#main 404 Not Found get /
after hash
```

The third test, it repeats the middle #main lines twice, the fourth test, three times, etc.

Looks like there is an "app" hanging around, holding onto #main, even thought app.isRunning() gives false, and Sammy.apps gives two entries "body" and "#main", both of which give isRunning() = false.

How do I debug this?

**Comment by endor** [comment]
That is a good question. I had some problems with that myself. Do you unload the app after running it? That usually helps. If nothing else helps you could destroy the app by removing the reference from Sammy.apps, though that shouldn't really be necessary. You could also run the app on another id. But all the existing tests should be fine without any changes. That should only apply when you add new ones. So for debugging.. check if the events being run are from the same app (app with the same id) as the app that was previously used. Check why it does not unload correctly. It might take a while to debug, but it's usually worth the effort.

**Comment by deitch** [comment]
At least I am not alone in this!

It is actually happening in the test files, in application_spec.js. I didn't write a single test for this yet, first making sure the original functionality works.

Looks like I need to dig into how it sets handlers under the covers to figure it out. The real frustrating part is that of what I have changed, this part should not be affected at all!

**Comment by deitch** [comment]
Well, I have at least part of it. app.unload() is not being properly called. I think it is because the callbacks are not going through correctly, and one leads to the next.

**Comment by deitch** [comment]
Right. Because app.unload() is inside the route, but the it() sets up app.run(), if the routes fail, then it keeps building up apps. Solution to that part is afterEach(function(){app.unload();});

app.unload() is safe anyways, because it checks if the app is running.

Now I need to figure out why the routes are failing, but at least it is sane now.

**Comment by deitch** [comment]
Ever do something incredibly stupid? Like going through an array of items (in this case, callback functions), and incrementing your counter i++ _before_ you run the first one, rather than after? Amazingly, things break! (feeling sheepish).

**Comment by deitch** [comment]
OK, this is just about done; putting touches in README.md

I will put in the pull request, and simultaneously close this issue.

As I do README.md - OK if I add my name to the contributors of additional features and fixes in there?

**Comment by deitch** [comment]
Done. Closing this out.

https://github.com/quirkey/sammy/pull/170

**Comment by deitch** [comment]
OK, the pull is in. Please comment on it.
