### ISSUE TITLE
hash proxy binding

### ISSUE THREAD

**Issue by dready92** [quirkey/sammy#17]
On firefox (didn't test others), there is an issue using $.sammy("app").location_proxy.bind()|unbind().
You are using jQuery die() method to unbind, which does not seem to unbind events added with the bind() method. On the doc you find that die() is to use remove events handlers attached with live.

```
unbind: function() {
    $(window).die('hashchange.' + this.app.eventNamespace());
},
```

Mickael

**Comment by quirkey** [comment]
Unbind, not die() for the location proxies. Closed by 15d22998c455d2d99ee0b9eed8d9ef64f9a2b3d6 [Thanks dready92]
