### ISSUE TITLE
Return value of before()

### ISSUE THREAD

**Issue by bpeterbremen** [quirkey/sammy#177]
We would like to cancel a route request in sammy. Therefore we use before() and return a false value. The problem is that the route is cancelled not just for this request but also for all future requests. 

Is there a way to reset the route that it is not blocked any more?

**Comment by endor** [comment]
I am not entirely sure what you mean. You always return false in the before()? Or the route is not even executed if you return true? Do you have example code?

**Comment by bpeterbremen** [comment]
Well, we have a page with a form and when a users wants to leave page (change url) but the form is not filled correctly the leaving should be intercepted. Therefore we use before() and return false whenever form is not filled correctly so the routing is cancelled. But when the user fills the form after taht and then tries to leave the page again towards the same url the before-method is not called since the route is still blocked.

**Comment by endor** [comment]
Do you have example code so I can help debug?

**Comment by bpeterbremen** [comment]
<pre>
<script type="text/javascript">
    $(document).ready(function () {
        var counter = 1;
        var app = Sammy('#main', function () {
            function canLeavePage() {
                if (counter % 3 == 0) {
                    return false;
                }
                return true;
            }
            this.before("#/test", function () {
                return canLeavePage();
            });
            this.get('#/test', function () {
                $('#counter').html("test " + counter);
                counter = counter + 1;
            });
        });
        app.run('#/');
    });
</script>
</pre>

Call -> Output:
index.html#/test -> test 1
index.html#/other
index.html#/test -> test 2
index.html#/other
index.html#/test -> test 2
index.html#/other
index.html#/test -> test 2

**Comment by endor** [comment]
Maybe you can comment a little bit on this example code. Are you wondering why there is always "test 2" and the number doesn't increase? That does make sense and has nothing to do with sammy, right? The route is only "blocked" because you always return false in canLeavePage after the counter arrived at 3.

**Comment by bpeterbremen** [comment]
Well, now I must admit the example was not good. But the problem is still present how to cancel a route based on current business-state of the page (e.g. data not saved). When I return false within before() function then route is cancelled but the new hash stays in browsers address bar. After that it is not possible to fire the route again, even if the state has changed.

**Comment by endor** [comment]
Well, yes, I guess that's true, but don't you think it would be a bit presumptuous of sammy to just return to the previous hash if the before returns false? What do you think about returning false in the before and redirecting to the previous hash yourself (in the before)?

**Comment by bpeterbremen** [comment]
We have setup a new demo showing our problemes with route cancelling. Maybe you want to have a look:
http://dl.dropbox.com/u/5400626/sammy/SammyCancelRoute.html

**Comment by quirkey** [comment]
@bpeterbremen the correct thing to do is do a `redirect()` in your `before()` before returning `false`. By the time the `before()` is executing the hash/location has already changed and that's what triggering the route run in the first place. You can redirect() to the location of your choice in the filter. The common example is with login - if the user is not logged in, redirect to a login page in a before filter and return false so that the user can not see the protected page.

**Comment by bpeterbremen** [comment]
Exactly this is what we do. Maybe you want to have a look at my second example: We use  app.setLocation(currentHash) in before() to return to the current saved hash. Indeed we want to stay on the same page and not to navigate to a third page (like in your login-example). But we encountered several issues under IE10 and Chrome like documented in the our example. Seems to be like hash change detection is broken after redirecting in before(). Actually I thought it is by design so this was my original question but now I think it might be a bug depending on different browser usage.
