### ISSUE TITLE
how to use sammyjs  on safari of the iphone?

### ISSUE THREAD

**Issue by ghost** [quirkey/sammy#178]
What matters need attention?

**Comment by endor** [comment]
I am not sure what you mean? Are you experiencing problems?

**Comment by ghost** [comment]
thank you for your reply. my problems have been solved.  It's about click
event on touch pad. I replaced click event to touchend event.

2013/1/15 Frank Prößdorf notifications@github.com

**Comment by endor** [comment]
Can you please close this?
