### ISSUE TITLE
TodoMVC example

### ISSUE THREAD

**Issue by jchannon** [quirkey/sammy#182]
Hi!

I really like the look of Sammy probably because of the Sinatra base, I contribute to Nancy a Sinatra based .Net web framework. http://nancyfx.org

Anyhow, I have started looking at JS more and came across TodoMVC and Sammy.

I started to write a Todo example for Sammy as I saw there wasn't one however I came up with some questions which I hope I can answer here.

Comparing the other Todo examples, frameworks like Backbone, Angular & Knockout have model tracking so when a item in a collection of todo's is modified, things like the number of items and properties like 'completed' are automatically bound to HTML elements.

I can see how I could do that and that's with jQuery so I'd have a form that would post, Sammy would pick it up and my JS would update the collection and jQuery could update HTML elements or I could re-render a template with Moustache with the modified collection.

Is that how you'd see it or have I missed a whole chunk of Sammy regarding model?

Thanks for your help

**Comment by endor** [comment]
I don't think a ticket is the right place to discuss this. In general I don't think you missed something. There's nothing related to models in sammy. You can either write your own model code or - like some other people - use sammy with  for example backbone and let backbone handle the models. Isn't that the same with sinatra? It's also more of a routing framework.
