### ISSUE TITLE
DefaultLocationProxy issue detecting HTML5 History

### ISSUE THREAD

**Issue by mikekidder** [quirkey/sammy#187]
I noticed that the bind for "DefaultLocationProxy" is not turning off the polling when the browser does have support for HTML5 History.

```
  $(window).bind('hashchange.' + this.app.eventNamespace(), function(e, non_native) {
    // if we receive a native hash change event, set the proxy accordingly
    // and stop polling
    if (proxy.is_native === false && !non_native) {
      proxy.is_native = true;
      window.clearInterval(lp._interval);
      lp._interval = null;
    }
    app.trigger('location-changed');
  });
```

The second argument in the anonymous callback function "non_native" is returning TRUE when I tested in recent browsers (tested both IE 10, Chrome 25+), so the if block is not executed.

Tried in both hello_world example, and a recent SPA template.  I couldn't find any examples on JQuery having two arguments.   Most are simply  -   function(e) { ... }

**Comment by forforeach** [comment]
I detected same issue. In my chrome browser it still falls back into a polling of hash. I think that when you trigger an 'hashchange' event, you must to pass it 'onhashchange' in window. This will trigger the event with parameter that actually indicate whether the browser supports 'onhashchange' event or not.

<pre>
<code>
var hashCheck = function() {
     var current_location = proxy.getLocation();
     if (typeof Sammy.DefaultLocationProxy._last_location == 'undefined' ||
                                  current_location != Sammy.DefaultLocationProxy._last_location) {
            window.setTimeout(function() {
                // !('onhashchange' in window) => non_native
               $(window).trigger('hashchange', [!('onhashchange' in window)]);
            }, 0);
     }
     Sammy.DefaultLocationProxy._last_location = current_location;
};
</code>
</pre>
