### ISSUE TITLE
Templates not cached on initial template loading

### ISSUE THREAD

**Issue by iffius** [quirkey/sammy#19]
After I turned caching on, I noticed that the same template was getting loaded multiple times when rendering partials.

Investigating this further, I saw that the ajax call hadn't returned before the next call to render the partial, so another ajax request request was made.  

In our application, we were looping over a number of elements and this caused a considerable slowdown that made it seem like the application wasn't loading on iphone/android web browsers.

My fix was to defer a callback if the initial ajax call to load the template hadn't returned.

http://github.com/iffius/sammy/commit/a82198406810f4666195fc39051986bb7efea2e5

Cheers,

**Comment by quirkey** [comment]
Hey Iffius 
this is a known issue with the current way templates work. I'm working on a revamp of the templating system that should fix this and a lot of other issues. I'll be posting on the mailing list for feedback shortly. I could pull this in now, but I'd rather fix a lot of the other issues too. Currently, the way to get around the async partial loading when rendering a 'collection' of elements is to pass an Array to the data param of partial, which will only fetch the template once.
--AQ

**Comment by quirkey** [comment]
This was changed fixed in 0.6 / RenderContext
