### ISSUE TITLE
Add closure to before()

### ISSUE THREAD

**Issue by jduv** [quirkey/sammy#192]
This is a feature request.

Although app.around() is fantastic for executing some piece of logic before each route and deciding on where you want the application to go, it would be even better if we had the path matching capabilities of the app.before() call. Example, I wish to check to see if a user is logged in and redirect if not on all pages except for the login and signup hash tags.

Yes, I can achieve this easily using other methods, but as a matter of convenience and from a design standpoint it seems like the closure callback should be passed on app.before() anyway, just like it is in app.around().

Feel free to close this if you disagree :). I can implement it too if you wish.

**Comment by alanjames1987** [comment]
+1

**Comment by alanjames1987** [comment]
Are you saying `.before`'s functionality should change or `.around`'s?

**Comment by alanjames1987** [comment]
If you use `.around` the `this` variable is the Sammy application, which you can extract the path from.
