### ISSUE TITLE
Why is jQuery a dependency?

### ISSUE THREAD

**Issue by tregusti** [quirkey/sammy#195]
I skimmed the source and only found refs to jquery for some utils like `extend` and `trim` etc. I wanted to use Sammy in a mobile app and it's totally out of the question to use such a heavy lib as jquery then. Then again, Sammy isn't small either =)

**Comment by endor** [comment]
I think the main thing that jQuery is used for in sammy is event handling (bind/trigger). This can be done without jQuery, but nobody has had the time to do it yet. You are welcome to help us with that. (:

**Comment by tregusti** [comment]
Maybe another time =)

I'm going for creating my own lightweight routing lib right now… I might give up and try out sammy =)
