### ISSUE TITLE
IE doesn't call server side action when you press back.

### ISSUE THREAD

**Issue by jmogera** [quirkey/sammy#206]
So I have a issue with I have two steps: Step 1 and Step 2. I am able to go to Step 2 but when I press back Step 1 does get loaded but doesn't make a call to the server. This issue is only present in IE. Currently I am using IE10, but in compatibility mode the same issue is duplicated.

I have attached a example project. If you place a breakpoint in the "GetStep1" action in HomeController. You will see that the breakpoint doesn't get caught when press back in IE10. Please let me know what I am doing wrong.

Download example here:
http://sdrv.ms/19mrZL7

Stackoverflow (more detail):
http://stackoverflow.com/questions/19160234/ie-doesnt-call-server-side-action-when-you-press-back

**Comment by endor** [comment]
Issue is solved as in: http://stackoverflow.com/questions/19160234/ie-doesnt-call-server-side-action-when-you-press-back
