### ISSUE TITLE
IE8 and F12 Developer Tools console error

### ISSUE THREAD

**Issue by PsySecCorp** [quirkey/sammy#211]
When running IE>8 in IE8 compatibility mode while having the F12 Developer Tools open, the following error occurs in Sammy v0.7.4:

```
Sammy.js Line 110: Object doesn't support this action
```

So to fix it, I recommend the following (https://github.com/quirkey/sammy/blob/master/lib/sammy.js#L110):

```
if (typeof window.console.log === 'function' && _isFunction(window.console.log.apply)) {
```

As `apply` doesn't work on objects, only functions.  Obligatory IE is butt, etc.

**Comment by purtuga** [comment]
I hit this same problem with IE11... Implemented the fix above and it works... Hopefully @quirkey can incorporate in next version.

Thanks @CodeOtter
