### ISSUE TITLE
500 Error 'params is not defined' when using Route parameters

### ISSUE THREAD

**Issue by msokk** [quirkey/sammy#22]
The 'context' variable isn't the first transparent argument to the callback, so the params variable is undefined.

get('#/by_name/:name', function() { //Works with function(context)
  alert(params['name']); //and with this.params
});

**Comment by quirkey** [comment]
Hey msokk

params is defined in the context, but context is explicit in JS so you have to do:

```
this.params['name']
```

--AQ

**Comment by quirkey** [comment]
Whoops! Thanks for the catch. Docs have been updated.
--AQ
