### ISSUE TITLE
inline template with mustache, not working with method_alias

### ISSUE THREAD

**Issue by efleming969** [quirkey/sammy#23]
var app = $.sammy(function() {

  this.use(Sammy.Mustache);           // works fine
  this.use(Sammy.Mustache, "ms"); // not working: this.mustache is not a function

  this.get('#/', function(ctx) { 
    ctx.log(this.mustache("hello, {{name}}", {name:"foo"}));
  });

});

**Comment by quirkey** [comment]
method_alias actually renames the base interpolation method for Sammy.Mustache (works the same way with Sammy.Template) In your above example, this would work:

   ctx.log(this.ms("hello, {{name}}", {name:"foo"}));
