### ISSUE TITLE
Including Sammy breaks jquery fileupload

### ISSUE THREAD

**Issue by mgregory22** [quirkey/sammy#232]
When I include Sammy on my page, I can no longer select a file for the Jquery FileUpload [https://github.com/blueimp/jQuery-File-Upload] plugin.  The file selection dialog pops up, but when I hit OK, it doesn' t show the file name I selected and clicking the upload button doesn't do anything.  There's no error reported in the console.

If I remove the `<script src="/Scripts/sammy-0.7.5.js"></script>` tag, it works fine.  Or if I remove this code it works fine:

```
    $(function() {
        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
            url: '/AnimatedGifs/FileHandler',
            acceptFileTypes: /gif$/i, // Allowed file types
        });
    });
```

I've tried calling $.noConflict() and replacing all the $'s to jQuery, but that didn't have any effect.

**Comment by endor** [comment]
Can't really reproduce. If you set up a sample repository, I can help you debug this.

**Comment by mgregory22** [comment]
Gah!  As I was setting up the sample project, it started working for some reason.  Thanks anyway for the reply!  Sorry for wasting your time!
