### ISSUE TITLE
Need event for when partial has finished rendering

### ISSUE THREAD

**Issue by ghost** [quirkey/sammy#26]
I am having a problem whereby there doesn't seem to be any way to provide a callback to the "partial" function that is called when a template has finished rendering. I understand that a callback is called when a collection is supplied, however I need to bind an event to an item that is being rendered in a partial and don't want to resort to timeouts... Am I missing something?

```
context.partial('my.template', { tasks: data });
app.trigger('make-list-sortable'); // this needs to be delayed until the list is in the DOM
```

I don't have a lot of hair left due to this one ;)

**Comment by quirkey** [comment]
You can pass a callback as the third argument of partial. The only difference is you'll have to place the template yourself. So something like:

```
    context.partial('my.template', {tasks: data}, function(html) {
       context.swap(html);
       context.trigger('make-list-sortable');
    });
```

Should work. Also, theres been a lot of work on a re-write of the template handling here:

http://github.com/quirkey/sammy/tree/render-context

Theres a lack of documentation for it (coming soon) but it aims to fix the API for the problem you've been having.

**Comment by ghost** [comment]
Aha yes, didn't realise you had to deal with updating to content yourself when a callback is supplied... makes perfect sense now.

Thanks for an awesome project, I'm in love with Sammy :) ...no doubt I will find a way to contribute in the near future. You may be interested in Ramble (http://github.com/soniciq/ramble), in early stages at the moment but could be useful for testing Sammy apps, it's a kinda client-side Cucumber. I hope to get it to a more complete state over the next couple of months.
