### ISSUE TITLE
Templates not html escaping strings, possible XSS problems

### ISSUE THREAD

**Issue by ghost** [quirkey/sammy#27]
I've just noticed that templates do not escape the interpolated values by default, there is an ugly workaround but I really don't like it:

```
<%= $('<div/>').text(my_variable).html() %>
```

I think these should be escaped by default like Rails 3, or there should at least be a way to escape via a simple function.

p.s. is there a way to user the 'partial' function inside another partial as this doesn't work:

```
<%= partial('blah') %>
```

**Comment by quirkey** [comment]
I forgot to update this ticket, but I added a escapeHTML() method to Sammy.Object (hence the EventContext, too). It's in /master now.

**Comment by ghost** [comment]
I noticed that afterwards actually, sorry I should have updated the ticket.

By the way, I'm loving the new render and load methods, cleans stuff up loads.

Thanks,

Jamie
