### ISSUE TITLE
Routes not working as documented

### ISSUE THREAD

**Issue by ghost** [quirkey/sammy#28]
The docs state that "Paths can be either full URIs (eg. /blah/blah/blah) or just the end hash (eg. #/mypath)". I can't get anything before the # to work. In the following, neither alerts happen when visiting '/my/url' or '/my/url#/thing'. The '#/foo' path works fine:

```
this.get('/my/url', function(context) {
  alert('Howdy 1');
});

this.get('/my/url#/thing', function(context) {
  alert('Howdy 2');
});

this.get('#/foo', function(context) {
  alert('Howdy 3');
});
```

**Comment by rainerborene** [comment]
Here is a related topic about this issue:
[http://groups.google.com/group/sammyjs/browse_thread/thread/44cec3f82a66b8e1](http://groups.google.com/group/sammyjs/browse_thread/thread/44cec3f82a66b8e1)

**Comment by ghost** [comment]
The trouble with the path location proxy is that it only takes into account the path and not the hash therefore something like '/my/url#/thing' doesn't work.

**Comment by quirkey** [comment]
This has been re-addressed (and fixed) in the next version of Sammy - you can check it out here: https://github.com/quirkey/sammy/tree/non-hash
