### ISSUE TITLE
window.location change detection is not working

### ISSUE THREAD

**Issue by mikeal** [quirkey/sammy#29]
For some reason the HashLocationProxy isn't working for me.

I added some console.log() messages to the interval and it appears as though as soon as the location actually changes the interval stops firing. It's quite odd.

My code is here:

http://github.com/mikeal/couchdb/tree/sammy

share/www/index.html
share/www/sammy/app.js

**Comment by quirkey** [comment]
Hey Mikeal

app looks great - really excited about this. What browser are you in? Whats the easiest way for me to test this? Can I just pull down the tree and open www in a browser?
Thanks --AQ

**Comment by mikeal** [comment]
I tried in Safari, Firefox and Chrome.

It kinda does need the CouchDB API to run so you'll have to pull down the branch and.

./bootstrap && ./configure && make && make dev

Then run.

./utils/run

Then just pull up http://localhost:5984/_utils

-Mikeal

**Comment by quirkey** [comment]
Hey 

I think I know the deal. You need to actually do the .run() after the dom has loaded. Like:

```
  $(function() { app.run(); });
```

Because it needs to bind the events to the DOM. I tried to build couchdb myself, but having trouble getting the dependencies to work. I'll hit you up on IRC soon.

**Comment by mikeal** [comment]
That fixes it. Thanks!
