### ISSUE TITLE
Use onpopstate for better URLs

### ISSUE THREAD

**Issue by rkh** [quirkey/sammy#31]
Just an idea. That way ppl wouldn't even notice it's sammy: http://www.spoiledmilk.dk/blog/?cat=10

**Comment by stereobooster** [comment]
with possibility to fallback to hashes
    get('/product')
    if html5 
      sammy will react to /product
      if( #/product  )
        location.Replace(/product);
    else
      sammy will react to #/product  

this can help http://github.com/fortes/history.js/

**Comment by quirkey** [comment]
html5 pushstate is now supported seamlessly in the next version of Sammy (0.7). you can check it out before its released https://github.com/quirkey/sammy/tree/non-hash
