### ISSUE TITLE
Redirect to same hash url but different verb does not work

### ISSUE THREAD

**Issue by wvl** [quirkey/sammy#36]
```
this.get('#/users', function(e) {   }

this.post('#/users', function(e) {
  e.redirect('#/users')  // this does nothing
}
```

I was a bit surprised that this didn't work -- posting to a collection to create a new item, then redirecting back to the collection does not work, since the hash does not change.

**Comment by quirkey** [comment]
I've definitely used this pattern before and seen it work. What browser/version are you testing in? I'll write a test to confirm its working on my side.

**Comment by wvl** [comment]
Chrome 6 osx with Sammy 0.6.1.  

Note that if I change that redirect url to something different,the redirect happens. But just changing verbs does not work. Thanks.

**Comment by quirkey** [comment]
I think this broke fairly recently, but added a test and a fix to master: 
http://github.com/quirkey/sammy/commit/960ee90eb98c947bdbcf1885a936b487e23006b5
Let me know if it fixes it for you.

**Comment by wvl** [comment]
That fixed it. Thanks!
