### ISSUE TITLE
Sammy and SEO + Analytics Tracking

### ISSUE THREAD

**Issue by rmdort** [quirkey/sammy#39]
Can Sammy driven pages be seo indexed and tracked using GA?

**Comment by quirkey** [comment]
Two different things:

For tracking, theres a google analytics plugin.

http://github.com/britg/sammy-google-analytics

If you look at the source, however, you'll notice that its pretty easy to do yourself as well.

For SEO, there have been a bunch of discussions on the mailing list about it. There are two main strategies, 1 - if you're using sammy for an app behind login, then SEO doesnt actually matter. 2 - If its a marketing or information site, you should pretty much always make you're site work without JS first and then add JS/Sammy after. If you're site works without JS then its no problem. 3- If you simply have to always use AJAX/JS google just released a spec on how to do 'AJAX Crawlable sites' which is pretty straight forward with Sammy and just requires some extra work on the server side: http://code.google.com/web/ajaxcrawling/docs/getting-started.html
