### ISSUE TITLE
URL Encoding

### ISSUE THREAD

**Issue by kbuckler** [quirkey/sammy#47]
Hey, first of all, thanks for such a great library! We're really excited about Sammy and are incorporating it into lots of projects at my company.

Anyhoo, when a form is submitted to an Sammy application, the form fields are form encoded and set to the Location hash. 

For example:

```
<form id="live_form" action="#/live" method="get">
    <input name="spaces" type="text" value="value with spaces" />
    <input name="pluses" type="text" value="+++" />
    <input type="submit" class="submit" />
</form>
```

Sets the location as follows:

```
#/live?spaces=value+with+spaces&pluses=%2B%2B%2B
```

... and is decoded as:

```
params['spaces'] => "value+with+spaces"
params['pluses'] => "+++"
```

So, at this point, we can't tell the difference between and space and a plus character. There are possibly other aliasing issues as well. I've mended this, but don't know if/how this will impact other users.

**Comment by quirkey** [comment]
This was fixed a while ago. Closing ticket
