### ISSUE TITLE
partial system doesn't cache templates

### ISSUE THREAD

**Issue by jonmagic** [quirkey/sammy#5]
I guess this is more of a feature request than anything. The partial method doesn't cache templates the first time it uses them, and I think because of that fails to render large groups of "items" consistently because its loading the template each time.

My example is I'm looping thru an array of 12 objects, and rendering each one using the partial method. The number it actually renders jumps all over the place. If I place a counter with an alert into the loop it alerts on all 12 and displays all 12, I guess because the alert slows it down.

**Comment by quirkey** [comment]
@jonmagic: What version of Sammy are you using? Starting in 0.3 partial doesnt cache by default, you need to include the Sammy.Cache plugin and caching should happen automatically then. Let me know if that still doesnt work.
