### ISSUE TITLE
Changing #<route> to #!<route> For Google's Crawlable Ajax Feature 

### ISSUE THREAD

**Issue by seflless** [quirkey/sammy#50]
hi,

Is it possible to switch the convention to using #! and then routh instead of # and then the route?

I'm starting a lib, where I'll be working on getting my site working with Google's Crawlable Ajax Feature:
http://code.google.com/web/ajaxcrawling/docs/getting-started.html

Francois

**Comment by frank06** [comment]
Yea, Twitter also uses that convention, e.g. http://twitter.com/#!/aq

**Comment by quirkey** [comment]
route paths are just strings or regular expressions, so theres no reason that you cant do this right now. 

```
 this.get('#!/aq', function() .. )
```
