### ISSUE TITLE
routes not based on hash aren't working

### ISSUE THREAD

**Issue by mikeal** [quirkey/sammy#51]
In the Docs:

get('/test/123', function() { 
  ...
});

But I'm not seeing this work at all, getLocation returns '' when the hashtag is omitted and I can't find out where the code is that would implement this, which sucks because I really need it :)

**Comment by mikeal** [comment]
This is a patch I'm using locally, it's not against the current master tho.

diff attachments/sammy/sammy.js ../oak.js/attachments/sammy/sammy.js 
902,910d901
<             route._path = path;
<             return false;
<           }
<         });
<         // Also check against the base path
<         $.each(this.routes[verb], function(i, route) {
<           if (app.routablePath(window.location.pathname).match(route.path)) {
<             routed = route;
<             route._path = window.location.pathname;
951a943

> 953c945
> 
> ## <       
> 
> 957c949
> 
> ## <         if ((path_params = route.path.exec(this.routablePath(route._path))) !== null) {
> 
> ```
>     if ((path_params = route.path.exec(this.routablePath(path))) !== null) {
> ```

**Comment by quirkey** [comment]
This is merged back to the original way of doing things (plus pushstate support) in the non-hash branch https://github.com/quirkey/sammy/tree/non-hash which will be in Sammy 0.7
