### ISSUE TITLE
Documentation code is mangled

### ISSUE THREAD

**Issue by victorbstan** [quirkey/sammy#52]
The code examples in the documentation are greatly mishappen, for example:

  &lt;h1&gt;{{title}}&lt;h1&gt;

```
   Hey, ! Welcome to Handlebars!
```

Wat's up with that? Why not just use gists for displaying code in the documentation?

**Comment by victorbstan** [comment]
Wow, actually the misshapen code is rendered correctly by this here bug-tracker, and does not reflect how mangled up it is in the real documentation pages...

 &lt;h1&gt;{{title}}&lt;h1&gt;

there it is, escaped...

**Comment by quirkey** [comment]
The docs are actually generated directly from the source and recreating gists each time would be impractical. I've been improving the documentation rendering though and this should be fixed once the new site is up in the next week or two.

Thanks
