### ISSUE TITLE
Redirect not triggering new callback

### ISSUE THREAD

**Issue by jamesarosen** [quirkey/sammy#53]
I have the following routes:

```
var app = $.sammy('#main', function() {
  this.use(Sammy.NestedParams);

  this.get('#/', function(context) {
    if (some_boolean) {
      context.redirect('#/foo');
    } else {
      context.redirect('#/bar');
    }
  });
  this.get('#/foo', function() {
    alert('foo');
  });
  // ...
});

app.run('#/');
```

When I go to the page (and `some_boolean` is true), Sammy redirects me to `#/foo`, but the callback is never triggered. Do I have to also force some sort of event?

I get the following log messages:

```
[Tue Nov 09 2010 11:05:20 GMT-0800 (PST)] runRoute get #/
[Tue Nov 09 2010 11:05:20 GMT-0800 (PST)] native hash change exists, using
```

Going directly to `#/foo` as the first URL for the page has the expected results. Manually changing the URL to add `#/foo` _after_ Sammy has run the redirect does nothing. It's as though Sammy has stopped processing.

**Comment by dansondergaard** [comment]
I have a similar (if not the same) problem. Clicking a link for `#/groups/0` to load the details for a certain group causes nothing to happen before a manual refresh of the page. The callback for the route is never called. Running Chromium 13.0.777.0 (Developer Build 86768 Linux). Sammy says `native hash change exists, using`, could this be a browser problem?

**Comment by jamesarosen** [comment]
I think the problem is the ordering of the routes. The first route is a prefix of the one it redirects to, so it's just the first route that gets run over and over.

**Comment by quirkey** [comment]
Hey Guys
Can you give me some more info - sammy version, browsers, etc? There is a test for something similar to this in the sammy source. I'll try to create a striped down test case. There are known issues in general with doing run(X), then immediately redirect(Y) (loosing some back button support) that I'm hoping to work out in the next release. Unsure if this is related though.

**Comment by jamesarosen** [comment]
Mine was on Sammy 0.6.2, but as of right now I think it's a problem with the order in which I declared my routes. If I notice the problem again I'll put together a JSFiddle and attach it to this issue.

**Comment by kirkbushell** [comment]
Wondering if this still a problem for you guys? Have you tried using around filters?

**Comment by quirkey** [comment]
If this is still a problem that we can repro - please reopen

**Comment by raphaeleidus** [comment]
@quirkey I have run into a similar problem on certain devices, where going from /#foo?param=true to just /#foo does not trigger the callback. This was when using `context.redirect('/#foo')` if I use `window.location.hash = '#foo'` it worked as expected.
