### ISSUE TITLE
Add Sammy.Flash plugin

### ISSUE THREAD

**Issue by jamesarosen** [quirkey/sammy#55]
I have a site that I would like to use Sammy with. Each page change can result in one or more informational or error messages that should be displayed. Each page, though, displays the error messages in a slightly different way. So far I've been passing them in query parameters to the next Sammy action, but I'd prefer to use something more like the Rails Flash:

```
this.use(Sammy.Flash);

this.post('#/foos', function(context) {
  // ...
  context.flash.info = "Added Foo";
  context.redirect('#/foos');
});
this.get('#/foos', function(context) {
  // ...
  context.flash.now.info = 'Have you seen our new Baz feature?';
  $('#flash').html(context.flash.toHtml());
});
```

That is, there's a `context.flash` and a `context.flash.now`. `Sammy.Flash.prototype` would include a default `toHtml` implementation, but it would be easy to change.

I'm happy to work on this; I just wanted to get the idea started in a public place before I jumped in.

**Comment by mikespokefire** [comment]
Sounds wonderful! I'd definitely want and use something like this, would be willing to help you test it also if you need another pair of eyes.

**Comment by mkuprionis** [comment]
yeah, sounds cool, was also thinking I need smth like that. Looking forward to try this out!

**Comment by jamesarosen** [comment]
Available [here](https://github.com/jamesarosen/sammy/commit/fcf64bd23da74982709d8083b9f7ed9d4dcd4993)

**Comment by jamesarosen** [comment]
Has anyone had a chance to give this plugin a test spin? I have some refactoring to do today that will give me a chance to try it. I'd like to hear some other comments before trying to get it merged into the main project.

**Comment by quirkey** [comment]
This has been pulled.
