### ISSUE TITLE
Cannot run test suite

### ISSUE THREAD

**Issue by jamesarosen** [quirkey/sammy#56]
Opening `index.html` directly causes the following failure:

> XMLHttpRequest cannot load file://localhost/Users/jamesrosen/Projects/sammy/test/fixtures/partial.html. Origin null is not allowed by Access-Control-Allow-Origin.

Running `test/test_server` fares only slightly better. The request to `/fixtures/partial.template` fails because Sinatra doesn't have a MIME type for `.template` files.

**Comment by jamesarosen** [comment]
I tried adding the following to the definition of the `SammyTest` Sinatra application, to no avail.

```
before do
  unless Rack::Mime::mime_type('template', nil)
    Rack::Mime::MIME_TYPES['template'] = Rack::Mime.mime_type('html')
  end
end
```

(I also tried adding it just once before `SammyTest` was initialized, but that didn't work either.)

**Comment by jamesarosen** [comment]
Aha. `Rack::MIME` needs a `.` before its type. Adding

```
Rack::Mime::MIME_TYPES['.template'] = Rack::Mime.mime_type('.html')
```

works :)

**Comment by jamesarosen** [comment]
Resolved in https://github.com/jamesarosen/sammy/commit/e1d73b27cfe90799005ed6a70759b5589971647f

**Comment by quirkey** [comment]
Interesting. You definitely have to run ./test/test_server or you run into that Chrome-doesnt-allow-ajax-over-the-file-protocol-error you're seeing above. I havent had problems with the mime types though. Was it actually showing up as errors in the test suite? Or was it just the console was spitting out warnings?

**Comment by jamesarosen** [comment]
It was showing up as errors in the test suite, since the response returned from the server was a 404-not-found page rather than the actual template content. The additional MIME type aliases I added solve the issue. Perhaps it's a problem of which version of Rack is running.

**Comment by quirkey** [comment]
Pulled, closing.
