### ISSUE TITLE
Cache not honored in IE?

### ISSUE THREAD

**Issue by cromoteca** [quirkey/sammy#63]
Hi, I'm a newbie since I'm using Sammy since yesterday, but I'm pretty sure that there is a behavior difference between IE and Firefox/Chrome: in IE (version 8 in w7) when I use context.load with cache set to false, it still loads the cached version. Let me know if you need further details.

**Comment by quirkey** [comment]
Hey cromoteca 
The cache: option for load() just specifies whether or not the content is cached in a JS object in browser memory. That cache would expire after refresh. Unfortunately, in my experience IE caches AJAX responses heavily even if you or the headers tell it not to. The best way to get around this is to append a 'cache-buster' query string to each request URL (usually a timestamp). For example:

```
  this.load('/myfile.json', {data: {t: (new Date().getTime())})
```

which would result in something like:

```
  GET /myfile.json?t=1233412344
```
