### ISSUE TITLE
Sammy.template changes have broken Sammy.form

### ISSUE THREAD

**Issue by oliver-dungey** [quirkey/sammy#65]
If you download the demo for 0.6.2 and use the form from the documentation in the Sammy.form code everything works beautifully.

If you download the official 0.6.2 pack then forms do not work due to escaping problems.

If you look in the Sammy.template code at:

String(template) 
        .replace(/[\r\t\n]/g, " ") 
        .replace(/\"/g, '\"') 
        .split("<%").join("\t") 
        .replace(/((^|%>)[^\t]_)/g, "$1\r") 
        .replace(/\t=(._?)%>/g, "\",h($1),\"") 
        .replace(/\t!(.*?)%>/g, "\",$1,\"") 
        .split("\t").join("\");") 
        .split("%>").join("**_$$$**_.push(\"") 
        .split("\r").join("") 
        + "\");}return **_$$$**_.join('');"); 

... right in the middle there is h($1). Remove the h() and everything 
works fine. h() is a shortcut to escapeHTML. The notes against 
escapeHTML says "Escape HTML in string, use in templates to prevent 
script injection.". So it would appear that the updated code is 
protecting itself from itself and breaking the form plugin.

Not really sure how to progress my code.

**Comment by quirkey** [comment]
Allow for passing of options and {escape_html: false} to Sammy.Template

This allows for modifying of the default escaping behavior especially
for use with Sammy.Form. Closed by 28272d136921d01f6c75e8075f0102012d42f7ac
