### ISSUE TITLE
Form submission is different for get / post  (and related crash)

### ISSUE THREAD

**Issue by rprieto** [quirkey/sammy#71]
Hi,

I just found out the behaviour of form submission changes if the form uses `method="post"` or `method="get"`. The first one executes any original `onSubmit` handler, while the other one always ignores it.  This seems to come from the implementation of `_checkFormSubmission`.

Is this the expected behaviour?

A small demo of this behaviour is available here:
http://jsfiddle.net/4fKFG/1/

Note that if the form doesn't specify any method, `_getFormVerb` returns "get" in IE but seems to crash in Chrome and Firefox (thus never submitting).

**Comment by quirkey** [comment]
Hey rpreito
I think there are a couple of things going on here:
- GET and POST do preform slightly differently in sammy. As a rule we're trying to emulate the server/client model as closely as possible, so GET's will append the form values as a query string to the current location.
- The lack of an action in the form seems to throw sammy off - I dont know when you would have a form without an action specified, but I'll look into capturing that correctly.
- I dont see the crashing in Chrome or FF - is this in specific versions?
- I believe the problems with onSubmit being defined directly on the form and Sammy still intercepting have to do with the way jQuery handles the bubbling of the submit event. I can look into this, but I'm sort of curious what the use case for this is - maybe if I have a better idea I can address it in a better way.

Thanks

**Comment by rprieto** [comment]
Thanks for the quick reply. In fact there are two different issues, come to think about it I should have opened 2 tickets...

## About the crash

This happens when we don't specify a method explicitly on the form (the default value is get). `_getFormVerb` seems to crash systematically for me on the latest versions of Chrome / Firefox under Linux and Windows.

http://jsfiddle.net/EapFF/
`getAttribute('method')` returns null, which doesn't play well with `verb.toString()`

## About our use case

We use `<form>` for semantic reasons only, as a group of inputs. This allows us to call `form.reset()`, but the form will never be submitted. The values are read by some javascript code later on.

What we really want is to prevent submission (for ex. by the enter key), hence the `onSubmit="return false;"`. Is there another way in Sammy to prevent submission, for example by overriding the submit route, or `_checkFormSubmission`?

Thanks

**Comment by quirkey** [comment]
Thanks for the details.
Still very strange about the crashing. null or undefined `toString()` _should_ just return an empty string. I moved some code around in an attempt to improve this:
https://github.com/quirkey/sammy/commit/75c0e8708e2bcb4f21992eadb4bda8284f805c73

Re: your use case - theres actually a pretty easy way to do this: Make the action something like '#/null' and make an empty route for '#/null' and Sammy will capture the submit and automatically `return false` unless you explicitly tell it not to.

**Comment by rprieto** [comment]
Thanks, setting the action to an empty route worked perfectly!
