### ISSUE TITLE
Issues with Sammy 0.6.2 and jQuery 1.5

### ISSUE THREAD

**Issue by chrinaldini** [quirkey/sammy#76]
Is there any known issues with this combination?
I tried to upgrade jQuery 1.4.4 to 1.5 and Sammy did not work anymore, i use jQuery templates also.

**Comment by quirkey** [comment]
Can you be more specific about what isnt working? I havent had a chance to test the combination yet, but im interested to know.

**Comment by chrinaldini** [comment]
It looks like the first issue is that the templates aren't rendring so I'm not sure if it's the template plugin that does not work with jq 1.5 or Sammy.
Maybe it's when I load the json resource before rendering the template, since the ajax api has been rebuilt?
It does not thow an error so I don't have more information now.
Hope this can be fixed so jq 1.5 can be used with the new features.

Thanx!

**Comment by quirkey** [comment]
I finally just tested jQuery 1.5.2 and Sammy/master and all seems well. Please reopen this ticket if you find a specific issue.

**Comment by chrinaldini** [comment]
Thanks for your effort Aaron, but there is still an issue with jQuery templates and this upgrade. The output from the render is empty: context.render('myJQtemplate.tmpl').then(function(output) {

Just wanted to add that we use sammy for a rather large project, the Norwegian Postal service's new digital post www.digipost.no (the web application) and we hope you can help us out here...

Thanks!

**Comment by davidwisch** [comment]
I had a similar issue, the solution (hack) that worked for me is documented in this Google Groups post: http://groups.google.com/group/sammyjs/browse_thread/thread/d712b2276fd6b7fe

**Comment by chrinaldini** [comment]
Thanks for the possible solution!
Now jq 1.6 is out and we hope there will be a permanent solution to this so we can follow jq and sammy's newer versions.

**Comment by quirkey** [comment]
I think the problem then actually isnt Sammy - Its that you need to make sure you're server is serving your template files (by setting mime/type extensions) correctly for `.tmpl` files. You can see how we do that simply with our 'test_server' here:

https://github.com/quirkey/sammy/blob/master/test/test_server#L6-9 

Seeing how this seems to be a common issue - a Sammy based solution would be allowing all templates to have a 'dual' extenstion and using the first as the 'engine'. So for example:
`myJQtemplate.tmpl` would become `myJQtemplate.tmpl.html` and Sammy would take the `tmpl` as the engine and the server would probably be smart enough to serve the file as just plain old html.

**Comment by chrinaldini** [comment]
Thanks Aaron, this works like a charm!
