### ISSUE TITLE
support for local templates

### ISSUE THREAD

**Issue by rubiii** [quirkey/sammy#77]
hey aaron,

i'd love to use sammy with [jammit](http://documentcloud.github.com/jammit/) which supports packaging the templates instead of loading them via http. since sammy does not (yet?) support local templates, i hacked together a small workaround which extends the `render` method, loads the template and returns an object, tricking sammy to use it as a jquery element.

app: https://github.com/rubiii/sam/blob/master/public/javascripts/application.js  

workaround: https://github.com/rubiii/sam/blob/master/public/javascripts/sammy-jst.js

loading the templates upfront might be especially interesting for small applications with a few templates. i don't think it would require much code to do this and could try to implement a non-hacky version (without introducing a dependency on JST) if you think this is a good idea.

cheers,
daniel

**Comment by quirkey** [comment]
Hey daniel

I hadnt seen how jammit packages templates until just now and it presents an interesting problem. Sammy _does_ support packaging templates, just in a different (albiet more standard way) of being able to load them from DOM elements or <script> tags on the page. jQuery-tmpl and Mustache particularly work well this way. render() and partial() can take a string (the name of a template) or a jQuery or DOM element. The use case is simple, embed the template in a script tag on the page:

```
   <script id="name-template" type="text/mustache" data-engine="mustache">
      I'm a template named {{name}}.
    </script>
```

then in a route/helper, you can do:

```
     this.partial($('#name-template'), {name: 'NAME'});
```

I like this approach as it lets all the view logic be embeded with the rest of the view. With JST it looks like JST 'templates' are just functions, similar to the way we define template 'engines' in Sammy. In this way you might be able to use interpolate() directly (not tested):

```
     var rctx = new RenderContext(this);
     var engine = function(content, data) { return JST.nametemplate(data); }
     rctx.interpolate({name: 'NAME'}, engine).appendTo('#main');
```

Still ugly but perhaps a little less hacky?
