### ISSUE TITLE
On some web servers and using Firefox, Mustache templates can trigger XML parsing errors when being loaded

### ISSUE THREAD

**Issue by giacecco** [quirkey/sammy#83]
Dear All,
I believe I found an odd bug in Sammy's implementation of Mustache, or a strange Firefox behaviour triggered by something Sammy's implementation of Mustache does. 

The ingredients are: 
[whatever].mustache named templates
Sammy 0.6.3
JQuery 1.5
Chrome 9.0.597.102
Firefox 3.6.13
Safari 5.0.3
on MacOS 10.6.6

When I call the same page of mine on Safari and Chrome, the two behave correctly (see http://dl.dropbox.com/u/13837050/error1.png), while Firefox fails on line 243 of sammy.mustache.js (see http://dl.dropbox.com/u/13837050/error2.png). 

On that line of code all other browsers find a string in the 'haystack' variable, containing the code of my template, which is correct. Firefox instead has a 'Document' object there, and the call to indexOf obviously fails.

When I inspect the Document above, what I found are references to XML parsing errors! (see http://dl.dropbox.com/u/13837050/error3.png). Somewhere in Sammy something is trying to interpret my mustache template as an XML file!

I then noticed that the problem does not happen when I host the same code on a Google App Engine account. What's the difference with the same code being viewed by the same Firefox accessing the development webserver (GAE JDK's Jetty) on my Mac? 

My first guess is the web server. Could it be then a MIME issue of some sort that becomes an issue on Firefox only? 

That was the right answer. I tried renaming all the templates to the harmless ".html" extension, told Sammy to use "html" as the template extension, and everything started working on Firefox, too.

G.

**Comment by quirkey** [comment]
Yes. I'll add this to the FAQ, but basically you need to define mime/types from your server if you're going to server `.mustache` or other non-standard extensions (`.template`, etc).
