### ISSUE TITLE
Problem with Safari back button

### ISSUE THREAD

**Issue by carlojoerges** [quirkey/sammy#85]
hi,

there seems to be a problem with the safari back button behaviour.
when you go to a sammy.js page with safari e.g.:
http://nettuts.s3.amazonaws.com/763_sammyJSIntro/demo/index.html#/label/drafts

now navigate to another page (by clicking on a favourite or entering a new address). when the page is loaded click the back button. 

when you come back to the sammy.js page, the routing doesn't seem to work anymore. any ideas on this one?

best,
carlo

**Comment by quirkey** [comment]
Sorry for missing this. What version of Safari is this?

**Comment by carlojoerges** [comment]
no problem. the problem occurs at least in safari 5.0.3 / mac.
