### ISSUE TITLE
Handlebars Plugin Bug?

### ISSUE THREAD

**Issue by arlolra** [quirkey/sammy#86]
Hello,

I'm noticing a bug in the Handlebars plugin.
If I have a setup as follows,

```
var myvar = true;
var mylist = [1, 2, 3];

{{#mylist}}
  {{#../myvar}}true{{/../myvar}}
{{/mylist}}
```

output:

"true" will not be displayed.

However, the inverse works.

```
var myvar = false;
var mylist = [1, 2, 3];

{{#mylist}}
 {{^../myvar}}false{{/../myvar}}
{{/mylist}}
```

output: false false false

I thought that maybe it just wasn't recognizing the `../` notation for blocks.
But if I change `myvar = true` in the second example, then I again get no output.
So, clearly it is.

Also, I'm using the same template on the server side with express.js, hbs and handlebars,
and getting the expected behaviour. That's why I assume the problem is with the plugin. I haven't had time to debug it, maybe someone knows what's wrong.

Thanks.

**Comment by andriijas** [comment]
Note that the plugin uses an obsolete version of handlebars. Im thinking of updating it and make a  merge req but its not clear in the plugin what code is related to being the plugin and what code is actually handlebars.

**Comment by Phunky** [comment]
It would be good to have this updated to the latest version of Handlebarsjs, but I too also couldn't quite tell how sammy was referencing the handlebar functions, will need to read through the docs a bit more before I attempt to update it.

**Comment by arlolra** [comment]
I've put in a pull request that should fix this issue for everyone:
https://github.com/quirkey/sammy/pull/103

If you guys could try it out and let me know if it's working for you, that would help.
https://github.com/arlolra/sammy/blob/newhandles/lib/plugins/sammy.handlebars.js

Thanks.

**Comment by Phunky** [comment]
Oh thanks arlolra, i'll give it a go now :)

**Comment by arlolra** [comment]
resolved in 0.7.0

**Comment by searchinnerpeace** [comment]
I think I'm having the same issue with sammy version 0.7.1:

File: index.html

``` html
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>Hello</title>
  </head>
  <body>
    <div id='main'></div>
    <script src='javascript/jquery.js'></script>
    <script src='javascript/handlebars.js'></script>
    <script src='javascript/sammy.js'></script>
    <script src='javascript/hello.js'></script>
  </body>
</html>
```

File: hello.js

``` javascript
(function($){
  var app = $.sammy(function(){
    this.element_selector = '#main';
    this.use('Handlebars', 'hb');
    this.get('#/hello/:name', function(){
      this.title = 'Hello!';
      this.name = this.params.name;
      this.partial('template.hb');
    });
  });
  $(function(){
    app.run('#/');
  });
})(jQuery);
```

File: template.rb

``` html
<h1>\{\{title\{\}</h1>
Hey, {{name}}! Welcome to Handlebars!
```

Firefox debug:

``` console
[20:28:44.961] [Mon Mar 11 2013 20:28:44 GMT-0300] #main Plugin Error: called use() but plugin (Sammy.Handlebars) is not defined t is undefined (new TypeError("Plugin Error: called use() but plugin (Sammy.Handlebars) is not defined t is undefined", "http://localhost:3000/javascript/sammy.js", 8))
```

When I navigate to #/hello/:name, sammy (or handlebars) don't render {{property}} elements.

**Comment by trendsetter37** [comment]
+1 @searchinnerpeace I'm having the same issue.
