### ISSUE TITLE
Regex escaping in embedded javascript in templates

### ISSUE THREAD

**Issue by frank06** [quirkey/sammy#9]
No biggie. Usually when I include Javascript in my templates I just code normally. I found that a correct regex wasn't matching because of an unescaped character.

I'll show it with an example:

This is normal code in a .js file, later included in the template 

```
   return e.className.replace(/[^\d]/g, '');
```

when I put this code inside a template, however, the backslash needs to be escaped:

```
  return e.className.replace(/[^\\d]/g, '');
```

I'm submitting this issue mainly because it took me a while to figure out _why_ the regex was not matching.

**Comment by quirkey** [comment]
Theres a possibility this just wont work with the Sammy.Template function (which is based on John Resig's template method). I had to do a bunch of hacking around it already to support single and double quotes properly. I think it might be hard to support embedded JS.

**Comment by frank06** [comment]
Don't worry. Maybe something to include in the docs?
